AWSTemplateFormatVersion: "2010-09-09"
Description: "My CloudFormation Training template"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        -
          Key: Name
          Value: MyCFVPC
  
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/2
      AvailabilityZone: 'us-west-2a'
      VpcId: !Ref VPC
      Tags:
        -
          Key: Name
          Value: MyCFPublicSubnet
  
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: 'us-west-2b'
      VpcId: !Ref VPC
      Tags:
        -
          Key: Name
          Value: MyCFPrivateVPC

  InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          -
            Key: Name
            Value: MyCFInternetGateway

